# coding=utf-8
from datetime import datetime
from sqlalchemy.dialects.mysql import LONGTEXT

from aot.databases import CRUDMixin
from aot.databases import set_uuid
from aot.aot_flask.extensions import db


class AIRecommendation(CRUDMixin, db.Model):
    """
    Manages AI-recommended expansion keywords for user facility.

    Tracks recommendations generated by the AI system to expand
    the user's areas of focus. Users can accept (add to interests)
    or dismiss (exclude from future recommendations).

    One record per recommendation. Status transitions:
    pending -> (accepted | dismissed) -> resolved_at set

    Philosophy alignment:
    - P2_Co_Growth: Recommendations guide facility learning expansion
    - P4_User_Agency: Users control recommendations

    @phase active
    @stability stable
    """
    __tablename__ = "ai_recommendation"
    __table_args__ = {'extend_existing': True}

    id = db.Column(db.Integer, unique=True, primary_key=True)
    recommendation_id = db.Column(db.String(36), nullable=False, unique=True, default=set_uuid)

    facility_id = db.Column(db.String(36), nullable=False, index=True)

    # Recommended keyword (e.g., "CO2 Management")
    keyword = db.Column(db.String(100), nullable=False)

    # Natural-language rationale (e.g., "Related to your Temperature and Humidity focus")
    reason = db.Column(db.Text().with_variant(LONGTEXT, "mysql", "mariadb"), nullable=False)

    # Source interests this recommendation is based on (JSON list)
    # e.g., ["temperature", "humidity"]
    source_interests = db.Column(db.Text, default='[]')

    # Status: pending, accepted, dismissed
    status = db.Column(db.String(20), default='pending', index=True)

    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    resolved_at = db.Column(db.DateTime, nullable=True)

    def __repr__(self):
        return f"<AIRecommendation(facility_id={self.facility_id}, keyword={self.keyword}, status={self.status})>"
