"""add duration and end time to scheduler

Revision ID: 0cc46ac41727
Revises: fa3f6b126918
Create Date: 2026-02-18 15:36:40.452589

"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(__file__, "../../../..")))

# from alembic_db.alembic_post_utils import write_revision_post_alembic

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc46ac41727'
down_revision = 'fa3f6b126918'
branch_labels = None
depends_on = None


def upgrade():
    # write_revision_post_alembic(revision)

    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    cols = [c['name'] for c in inspector.get_columns('scheduler_jobs_meta')]

    with op.batch_alter_table('scheduler_jobs_meta', schema=None) as batch_op:
        if 'duration_sec' not in cols:
            batch_op.add_column(sa.Column('duration_sec', sa.Integer(), nullable=True))
        if 'end_time' not in cols:
            batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduler_jobs_meta', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('duration_sec')

    # ### end Alembic commands ###
