"""Expand AITask and add AITaskHistory for v2.0

Revision ID: 466a5358b695
Revises: fa3f6b126919
Create Date: 2026-02-19 23:47:42.936768

"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(__file__, "../../../..")))

# from alembic_db.alembic_post_utils import write_revision_post_alembic

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '466a5358b695'
down_revision = 'fa3f6b126919'
branch_labels = None
depends_on = None


def upgrade():
    # write_revision_post_alembic(revision)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_reason', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True))
        batch_op.add_column(sa.Column('linked_sensors', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True))
        batch_op.add_column(sa.Column('impact_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_routine', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('proposed_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('proposed_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_task', schema=None) as batch_op:
        batch_op.drop_column('proposed_end')
        batch_op.drop_column('proposed_start')
        batch_op.drop_column('is_routine')
        batch_op.drop_column('impact_score')
        batch_op.drop_column('linked_sensors')
        batch_op.drop_column('change_reason')

    # ### end Alembic commands ###
