"""add conversation threading to aihistory

Revision ID: 68e82f214733
Revises: f1c2c65e35cc
Create Date: 2026-02-19 09:14:06.723351

"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(__file__, "../../../..")))

# from alembic_db.alembic_post_utils import write_revision_post_alembic

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e82f214733'
down_revision = 'f1c2c65e35cc'
branch_labels = None
depends_on = None


def upgrade():
    # write_revision_post_alembic(revision)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_history_thread_id'), ['thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_history_thread_id'))
        batch_op.drop_column('message_type')
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
