"""temp_fix_mismatch

Revision ID: ab6d34a7621b
Revises: df003e457948
Create Date: 2026-03-07 10:47:16.950889

"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(__file__, "../../../..")))

# from alembic_db.alembic_post_utils import write_revision_post_alembic

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab6d34a7621b'
down_revision = 'df003e457948'
branch_labels = None
depends_on = None


def upgrade():
    # write_revision_post_alembic(revision)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pipeline_role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('model_tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tool_access', sa.String(length=20), nullable=True))

    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_type', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('is_activated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('position_y', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auth_username', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('auth_password', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('capture_mode', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('capture_settings', sa.JSON(), nullable=True))

    with op.batch_alter_table('conditional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_conditional_tab_id'), ['tab_id'], unique=False)
        batch_op.create_foreign_key('fk_conditional_tab_id', 'tab', ['tab_id'], ['unique_id'], ondelete='CASCADE')

    with op.batch_alter_table('custom_controller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_custom_controller_tab_id'), ['tab_id'], unique=False)
        batch_op.create_foreign_key('fk_custom_controller_tab_id', 'tab', ['tab_id'], ['unique_id'], ondelete='CASCADE')

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_sort_order'), ['sort_order'], unique=False)

    with op.batch_alter_table('function', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_function_tab_id'), ['tab_id'], unique=False)
        batch_op.create_foreign_key('fk_function_tab_id', 'tab', ['tab_id'], ['unique_id'], ondelete='CASCADE')

    with op.batch_alter_table('geo_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_map_category'), ['category'], unique=False)

    with op.batch_alter_table('geo_setting', schema=None) as batch_op:
        batch_op.alter_column('zoom',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('geo_shape', schema=None) as batch_op:
        batch_op.drop_index('ix_map_overlay_channel_id')
        batch_op.create_index(batch_op.f('ix_geo_shape_geo_id'), ['geo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_shape_type'), ['type'], unique=False)

    with op.batch_alter_table('input', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_input_tab_id'), ['tab_id'], unique=False)
        batch_op.create_foreign_key('fk_input_tab_id', 'tab', ['tab_id'], ['unique_id'], ondelete='CASCADE')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('target_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gps_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gps_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('parent_task_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notes_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_foreign_key('fk_notes_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_output_tab_id'), ['tab_id'], unique=False)
        batch_op.create_foreign_key('fk_output_tab_id', 'tab', ['tab_id'], ['unique_id'], ondelete='CASCADE')

    with op.batch_alter_table('pid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_pid_tab_id'), ['tab_id'], unique=False)
        batch_op.create_foreign_key('fk_pid_tab_id', 'tab', ['tab_id'], ['unique_id'], ondelete='CASCADE')

    with op.batch_alter_table('scheduler_jobs_meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_editable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deletable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edit_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_edited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_edited_by', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('deletion_reason', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True))
        batch_op.create_index(batch_op.f('ix_scheduler_jobs_meta_source_type'), ['source_type'], unique=False)

    with op.batch_alter_table('trigger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_trigger_tab_id'), ['tab_id'], unique=False)
        batch_op.create_foreign_key('fk_trigger_tab_id', 'tab', ['tab_id'], ['unique_id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=True)

    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_widget_tab_id'), ['tab_id'], unique=False)
        batch_op.create_foreign_key('fk_widget_tab_id', 'tab', ['tab_id'], ['unique_id'], ondelete='CASCADE')
        batch_op.drop_column('dashboard_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_widget_tab_id'))
        batch_op.drop_column('tab_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    with op.batch_alter_table('trigger', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_trigger_tab_id'))
        batch_op.drop_column('tab_id')

    with op.batch_alter_table('scheduler_jobs_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduler_jobs_meta_source_type'))
        batch_op.drop_column('deletion_reason')
        batch_op.drop_column('last_edited_by')
        batch_op.drop_column('last_edited_at')
        batch_op.drop_column('edit_count')
        batch_op.drop_column('is_deletable')
        batch_op.drop_column('is_editable')
        batch_op.drop_column('source_type')

    with op.batch_alter_table('pid', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pid_tab_id'))
        batch_op.drop_column('tab_id')

    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_output_tab_id'))
        batch_op.drop_column('tab_id')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notes_parent_task_id'))
        batch_op.drop_column('user_id')
        batch_op.drop_column('parent_task_id')
        batch_op.drop_column('gps_lng')
        batch_op.drop_column('gps_lat')
        batch_op.drop_column('target_type')
        batch_op.drop_column('target_id')

    with op.batch_alter_table('input', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_input_tab_id'))
        batch_op.drop_column('tab_id')

    with op.batch_alter_table('geo_shape', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geo_shape_type'))
        batch_op.drop_index(batch_op.f('ix_geo_shape_geo_id'))
        batch_op.create_index('ix_map_overlay_channel_id', ['channel_id'], unique=False)

    with op.batch_alter_table('geo_setting', schema=None) as batch_op:
        batch_op.alter_column('zoom',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('geo_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geo_map_category'))

    with op.batch_alter_table('function', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_function_tab_id'))
        batch_op.drop_column('tab_id')

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_sort_order'))

    with op.batch_alter_table('custom_controller', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_custom_controller_tab_id'))
        batch_op.drop_column('tab_id')

    with op.batch_alter_table('conditional', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conditional_tab_id'))
        batch_op.drop_column('tab_id')

    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.drop_column('capture_settings')
        batch_op.drop_column('capture_mode')
        batch_op.drop_column('auth_password')
        batch_op.drop_column('auth_username')
        batch_op.drop_column('position_y')
        batch_op.drop_column('is_activated')
        batch_op.drop_column('camera_type')

    with op.batch_alter_table('ai_agent', schema=None) as batch_op:
        batch_op.drop_column('tool_access')
        batch_op.drop_column('model_tier')
        batch_op.drop_column('pipeline_role')

    # ### end Alembic commands ###
