"""add_ai_error_feedback_table

Revision ID: ae15af502469
Revises: ee0d7d7a5ff4
Create Date: 2026-02-28 09:57:06.904344

"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(__file__, "../../../..")))

# from alembic_db.alembic_post_utils import write_revision_post_alembic

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae15af502469'
down_revision = 'ee0d7d7a5ff4'
branch_labels = None
depends_on = None


def upgrade():
    # write_revision_post_alembic(revision)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_error_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('incorrect_response', sa.Text(), nullable=False),
    sa.Column('user_correction', sa.Text(), nullable=True),
    sa.Column('user_comment', sa.Text(), nullable=True),
    sa.Column('context_snapshot', sa.Text(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('correction_applied', sa.Boolean(), nullable=True),
    sa.Column('reported_by', sa.String(length=50), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=50), nullable=True),
    sa.Column('added_to_knowledge_base', sa.Boolean(), nullable=True),
    sa.Column('added_to_glossary', sa.Boolean(), nullable=True),
    sa.Column('added_to_training_data', sa.Boolean(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['ai_history.unique_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_error_feedback', schema=None) as batch_op:
        batch_op.create_index('idx_error_type_severity', ['error_type', 'severity'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)
        batch_op.create_index('idx_thread_agent', ['thread_id', 'agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_error_feedback_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_error_feedback_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_error_feedback_history_id'), ['history_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_error_feedback_reported_at'), ['reported_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_error_feedback_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_error_feedback_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_error_feedback_unique_id'), ['unique_id'], unique=True)

    with op.batch_alter_table('ai_system_summary', schema=None) as batch_op:
        batch_op.drop_index('idx_anomaly_alert')
        batch_op.drop_index('idx_scope_active')
        batch_op.drop_index('idx_scope_timestamp')
        batch_op.drop_index('ix_ai_system_summary_unique_id')
        batch_op.create_index(batch_op.f('ix_ai_system_summary_unique_id'), ['unique_id'], unique=True)
        batch_op.create_index('idx_scope_time', ['scope_type', 'scope_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_system_summary', schema=None) as batch_op:
        batch_op.drop_index('idx_scope_time')
        batch_op.drop_index(batch_op.f('ix_ai_system_summary_unique_id'))
        batch_op.create_index('ix_ai_system_summary_unique_id', ['unique_id'], unique=False)
        batch_op.create_index('idx_scope_timestamp', ['scope_type', 'scope_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_scope_active', ['scope_type', 'scope_id', 'is_active'], unique=False)
        batch_op.create_index('idx_anomaly_alert', ['anomaly_detected', 'alert_level'], unique=False)

    with op.batch_alter_table('ai_error_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_error_feedback_unique_id'))
        batch_op.drop_index(batch_op.f('ix_ai_error_feedback_thread_id'))
        batch_op.drop_index(batch_op.f('ix_ai_error_feedback_status'))
        batch_op.drop_index(batch_op.f('ix_ai_error_feedback_reported_at'))
        batch_op.drop_index(batch_op.f('ix_ai_error_feedback_history_id'))
        batch_op.drop_index(batch_op.f('ix_ai_error_feedback_error_type'))
        batch_op.drop_index(batch_op.f('ix_ai_error_feedback_agent_id'))
        batch_op.drop_index('idx_thread_agent')
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_error_type_severity')

    op.drop_table('ai_error_feedback')
    # ### end Alembic commands ###
