"""Add custom_theme_json to misc

Revision ID: bf13ae52c93f
Revises: ae15af502469
Create Date: 2026-03-02 18:04:05.533910

"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(__file__, "../../../..")))

# from alembic_db.alembic_post_utils import write_revision_post_alembic

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf13ae52c93f'
down_revision = 'ae15af502469'
branch_labels = None
depends_on = None


def upgrade():
    # write_revision_post_alembic(revision)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('misc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_theme_json', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True))
        batch_op.drop_column('bg_upgrade')
        batch_op.drop_column('bg_pause')
        batch_op.drop_column('bd_btn_border')
        batch_op.drop_column('bg_btn_upgrade')
        batch_op.drop_column('bg_btn_active')
        batch_op.drop_column('text_color_secondary')
        batch_op.drop_column('text_color_tertiary')
        batch_op.drop_column('bd_btn_secondary')
        batch_op.drop_column('bg_mcp')
        batch_op.drop_column('bg_btn_on')
        batch_op.drop_column('bg_llm')
        batch_op.drop_column('bd_btn_tertiary')
        batch_op.drop_column('bd_primary')
        batch_op.drop_column('bd_tertiary')
        batch_op.drop_column('bg_inactive')
        batch_op.drop_column('bg_btn_hold')
        batch_op.drop_column('bg_btn_pause')
        batch_op.drop_column('brand_color_secondary')
        batch_op.drop_column('text_color_primary')
        batch_op.drop_column('bg_btn_inactive')
        batch_op.drop_column('brand_color_accent')
        batch_op.drop_column('bg_active')
        batch_op.drop_column('brand_color_primary')
        batch_op.drop_column('bd_btn_primary')
        batch_op.drop_column('bg_hold')
        batch_op.drop_column('bd_secondary')
        batch_op.drop_column('bg_btn_off')
        batch_op.drop_column('bd_border')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('misc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bd_border', sa.VARCHAR(length=7), server_default=sa.text("'#13261B'"), nullable=True))
        batch_op.add_column(sa.Column('bg_btn_off', sa.VARCHAR(length=7), server_default=sa.text("'#54b138'"), nullable=True))
        batch_op.add_column(sa.Column('bd_secondary', sa.VARCHAR(length=7), server_default=sa.text("'#F3F6F5'"), nullable=True))
        batch_op.add_column(sa.Column('bg_hold', sa.VARCHAR(length=7), server_default=sa.text("'#8d9fd8'"), nullable=True))
        batch_op.add_column(sa.Column('bd_btn_primary', sa.VARCHAR(length=7), server_default=sa.text("'#13261B'"), nullable=True))
        batch_op.add_column(sa.Column('brand_color_primary', sa.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('bg_active', sa.VARCHAR(length=7), server_default=sa.text("'#B3E2B6'"), nullable=True))
        batch_op.add_column(sa.Column('brand_color_accent', sa.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('bg_btn_inactive', sa.VARCHAR(length=7), server_default=sa.text("'#5E6B64'"), nullable=True))
        batch_op.add_column(sa.Column('text_color_primary', sa.VARCHAR(length=7), server_default=sa.text("'#13261B'"), nullable=True))
        batch_op.add_column(sa.Column('brand_color_secondary', sa.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('bg_btn_pause', sa.VARCHAR(length=7), server_default=sa.text("'#b1b1b1'"), nullable=True))
        batch_op.add_column(sa.Column('bg_btn_hold', sa.VARCHAR(length=7), server_default=sa.text("'#747474'"), nullable=True))
        batch_op.add_column(sa.Column('bg_inactive', sa.VARCHAR(length=7), server_default=sa.text("'#FFCBCA'"), nullable=True))
        batch_op.add_column(sa.Column('bd_tertiary', sa.VARCHAR(length=7), server_default=sa.text("'#13261B'"), nullable=True))
        batch_op.add_column(sa.Column('bd_primary', sa.VARCHAR(length=7), server_default=sa.text("'#FFFFFF'"), nullable=True))
        batch_op.add_column(sa.Column('bd_btn_tertiary', sa.VARCHAR(length=7), server_default=sa.text("'#F3F6F5'"), nullable=True))
        batch_op.add_column(sa.Column('bg_llm', sa.VARCHAR(length=7), server_default=sa.text("'#6277c7'"), nullable=True))
        batch_op.add_column(sa.Column('bg_btn_on', sa.VARCHAR(length=7), server_default=sa.text("'#b14130'"), nullable=True))
        batch_op.add_column(sa.Column('bg_mcp', sa.VARCHAR(length=7), server_default=sa.text("'#64c762'"), nullable=True))
        batch_op.add_column(sa.Column('bd_btn_secondary', sa.VARCHAR(length=7), server_default=sa.text("'#5E6B64'"), nullable=True))
        batch_op.add_column(sa.Column('text_color_tertiary', sa.VARCHAR(length=7), server_default=sa.text("'#FFFFFF'"), nullable=True))
        batch_op.add_column(sa.Column('text_color_secondary', sa.VARCHAR(length=7), server_default=sa.text("'#5E6B64'"), nullable=True))
        batch_op.add_column(sa.Column('bg_btn_active', sa.VARCHAR(length=7), server_default=sa.text("'#13261B'"), nullable=True))
        batch_op.add_column(sa.Column('bg_btn_upgrade', sa.VARCHAR(length=7), server_default=sa.text("'#13261B'"), nullable=True))
        batch_op.add_column(sa.Column('bd_btn_border', sa.VARCHAR(length=7), server_default=sa.text("'#5E6B64'"), nullable=True))
        batch_op.add_column(sa.Column('bg_pause', sa.VARCHAR(length=7), server_default=sa.text("'#d7cd9b'"), nullable=True))
        batch_op.add_column(sa.Column('bg_upgrade', sa.VARCHAR(length=7), server_default=sa.text("'#13261B'"), nullable=True))
        batch_op.drop_column('custom_theme_json')

    # ### end Alembic commands ###
