"""Add user_id to ai_history for per-user conversation isolation

Revision ID: c9e7b3a2f1d8
Revises: c3d4e5f6a7b8
Create Date: 2026-03-28 00:00:00.000000

REQ-1: Each conversation record must be associated with the authenticated user.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e7b3a2f1d8'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()
    columns = sa.inspect(connection).get_columns('ai_history')
    col_names = [c['name'] for c in columns]
    with op.batch_alter_table('ai_history', schema=None) as batch_op:
        if 'user_id' not in col_names:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        indexes = sa.inspect(connection).get_indexes('ai_history')
        idx_names = [i['name'] for i in indexes]
        if 'ix_ai_history_user_id' not in idx_names:
            batch_op.create_index(batch_op.f('ix_ai_history_user_id'), ['user_id'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table('ai_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_history_user_id'))
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
