"""Add AISystemSummary and AISystemSummaryFeedback tables

Revision ID: ee0d7d7a5ff4
Revises: dde09640a0a2
Create Date: 2026-02-25 15:04:56.561119

"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(__file__, "../../../..")))

# from alembic_db.alembic_post_utils import write_revision_post_alembic

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0d7d7a5ff4'
down_revision = 'dde09640a0a2'
branch_labels = None
depends_on = None


def upgrade():
    write_revision_post_alembic(revision)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_system_summary',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('unique_id', sa.String(length=36), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('summary_text', sa.Text(), nullable=False),
        sa.Column('scope_type', sa.String(length=20), nullable=False),
        sa.Column('scope_id', sa.String(length=50), nullable=True),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('previous_summary_id', sa.String(length=36), nullable=True),
        sa.Column('generation_time_ms', sa.Integer(), nullable=False),
        sa.Column('token_count', sa.Integer(), nullable=False),
        sa.Column('anomaly_detected', sa.Boolean(), nullable=True),
        sa.Column('alert_level', sa.String(length=10), nullable=True),
        sa.Column('change_summary', sa.Text(), nullable=True),
        sa.Column('quality_score', sa.Float(), nullable=True),
        sa.Column('metadata_json', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('unique_id')
    )
    op.create_index(op.f('ix_ai_system_summary_anomaly_detected'), 'ai_system_summary', ['anomaly_detected'], unique=False)
    op.create_index(op.f('ix_ai_system_summary_is_active'), 'ai_system_summary', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_system_summary_scope_id'), 'ai_system_summary', ['scope_id'], unique=False)
    op.create_index(op.f('ix_ai_system_summary_scope_type'), 'ai_system_summary', ['scope_type'], unique=False)
    op.create_index(op.f('ix_ai_system_summary_timestamp'), 'ai_system_summary', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ai_system_summary_unique_id'), 'ai_system_summary', ['unique_id'], unique=False)
    
    # Composite indexes for performance
    op.create_index('idx_scope_timestamp', 'ai_system_summary', ['scope_type', 'scope_id', 'timestamp'], unique=False)
    op.create_index('idx_scope_active', 'ai_system_summary', ['scope_type', 'scope_id', 'is_active'], unique=False)
    op.create_index('idx_anomaly_alert', 'ai_system_summary', ['anomaly_detected', 'alert_level'], unique=False)

    op.create_table('ai_system_summary_feedback',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('summary_id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=50), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('feedback_text', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['summary_id'], ['ai_system_summary.unique_id'], )
    )
    op.create_index(op.f('ix_ai_system_summary_feedback_summary_id'), 'ai_system_summary_feedback', ['summary_id'], unique=False)
    op.create_index(op.f('ix_ai_system_summary_feedback_user_id'), 'ai_system_summary_feedback', ['user_id'], unique=False)
    op.create_index('idx_summary_user', 'ai_system_summary_feedback', ['summary_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_summary_user', table_name='ai_system_summary_feedback')
    op.drop_index(op.f('ix_ai_system_summary_feedback_user_id'), table_name='ai_system_summary_feedback')
    op.drop_index(op.f('ix_ai_system_summary_feedback_summary_id'), table_name='ai_system_summary_feedback')
    op.drop_table('ai_system_summary_feedback')
    
    op.drop_index('idx_anomaly_alert', table_name='ai_system_summary')
    op.drop_index('idx_scope_active', table_name='ai_system_summary')
    op.drop_index('idx_scope_timestamp', table_name='ai_system_summary')
    op.drop_index(op.f('ix_ai_system_summary_unique_id'), table_name='ai_system_summary')
    op.drop_index(op.f('ix_ai_system_summary_timestamp'), table_name='ai_system_summary')
    op.drop_index(op.f('ix_ai_system_summary_scope_type'), table_name='ai_system_summary')
    op.drop_index(op.f('ix_ai_system_summary_scope_id'), table_name='ai_system_summary')
    op.drop_index(op.f('ix_ai_system_summary_is_active'), table_name='ai_system_summary')
    op.drop_index(op.f('ix_ai_system_summary_anomaly_detected'), table_name='ai_system_summary')
    op.drop_table('ai_system_summary')
    # ### end Alembic commands ###
