version: "3.7"

services:

  aot-ai_influxdb:
    container_name: aot-ai_influxdb
    build:
      context: ../
      dockerfile: docker/influxdb/Dockerfile
    env_file:
      - 'influxdb/env.influxdb'
    volumes:
      - aot-ai_influxdb:/var/lib/influxdb

  aot-ai_nginx:
    container_name: aot-ai_nginx
    restart: always
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - aot-ai:/usr/local/aot-ai
      - aot-ai_log:/var/log/aot-ai
      - aot-ai_ssl_certs:/home/aot-ai/aot-ai/aot-ai_flask/ssl_certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - aot-ai_flask

  aot-ai_daemon:
    container_name: aot-ai_daemon
    image: app
    restart: always
    environment:
      - TZ=America/New_York  # See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for valid time zones
    volumes:
      - aot-ai:/usr/local/aot-ai
      - aot-ai_env:/home/aot-ai/env
      - aot-ai_databases:/home/aot-ai/databases
      - aot-ai_cameras:/home/aot-ai/cameras
      - aot-ai_custom_functions:/home/aot-ai/aot-ai/functions/custom_functions
      - aot-ai_custom_actions:/home/aot-ai/aot-ai/actions/custom_actions
      - aot-ai_custom_inputs:/home/aot-ai/aot-ai/inputs/custom_inputs
      - aot-ai_custom_outputs:/home/aot-ai/aot-ai/outputs/custom_outputs
      - aot-ai_custom_widgets:/home/aot-ai/aot-ai/widgets/custom_widgets
      - aot-ai_custom_user_scripts:/home/aot-ai/aot-ai/user_scripts
      - aot-ai_log:/var/log/aot-ai
      - aot-ai_ssl_certs:/home/aot-ai/aot-ai/aot-ai_flask/ssl_certs
      - /dev:/dev
      - /sys:/sys
      - /opt:/opt
    privileged: true
    command: bash -c "wget --quiet --no-check-certificate -p http://aot-ai_nginx/ -O /dev/null && 
                      PYTHONPATH=/home/aot-ai /home/aot-ai/env/bin/python aot-ai_daemon.py"
    depends_on:
      - aot-ai_flask

  aot-ai_flask:
    container_name: aot-ai_flask
    image: app
    hostname: AoT-AI  # Change to your desired hostname
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    environment:
      - TZ=America/New_York  # See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for valid time zones
    volumes:
      - aot-ai:/usr/local/aot-ai
      - aot-ai_env:/home/aot-ai/env
      - aot-ai_databases:/home/aot-ai/databases
      - aot-ai_cameras:/home/aot-ai/cameras
      - aot-ai_custom_functions:/home/aot-ai/aot-ai/functions/custom_functions
      - aot-ai_custom_actions:/home/aot-ai/aot-ai/actions/custom_actions
      - aot-ai_custom_inputs:/home/aot-ai/aot-ai/inputs/custom_inputs
      - aot-ai_custom_outputs:/home/aot-ai/aot-ai/outputs/custom_outputs
      - aot-ai_custom_widgets:/home/aot-ai/aot-ai/widgets/custom_widgets
      - aot-ai_custom_user_scripts:/home/aot-ai/aot-ai/user_scripts
      - aot-ai_custom_user_css:/home/aot-ai/aot-ai/aot-ai_flask/static/css/user_css
      - aot-ai_custom_user_js:/home/aot-ai/aot-ai/aot-ai_flask/static/js/user_js
      - aot-ai_custom_user_fonts:/home/aot-ai/aot-ai/aot-ai_flask/static/fonts/user_fonts
      - aot-ai_log:/var/log/aot-ai
      - aot-ai_ssl_certs:/home/aot-ai/aot-ai/aot-ai_flask/ssl_certs
      - aot-ai_influxdb:/var/lib/influxdb
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Permits container to restart itself
    privileged: true
    command: /home/aot-ai/env/bin/python -m gunicorn --workers 1 --bind unix:/usr/local/aot-ai/aot-aiflask.sock start_flask_ui:app
    depends_on:
      - aot-ai_influxdb

# Uncomment the following blocks and rebuild to enable Grafana and/or Telegraf

#  aot-ai_telegraf:
#    image: telegraf:latest
#    container_name: aot-ai_telegraf
#    volumes:
#      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
#    depends_on:
#      - aot-ai_influxdb

#  aot-ai_grafana:
#    image: grafana/grafana:latest
#    container_name: aot-ai_grafana
#    env_file:
#      - './grafana/env.grafana'
#    volumes:
#      - aot-ai_grafana:/var/lib/grafana
#    ports:
#      - "3000:3000"
#    depends_on:
#      - aot-ai_influxdb

volumes:
  aot-ai:
  aot-ai_env:
  aot-ai_cameras:
  aot-ai_custom_functions:
  aot-ai_custom_actions:
  aot-ai_custom_inputs:
  aot-ai_custom_outputs:
  aot-ai_custom_widgets:
  aot-ai_custom_user_scripts:
  aot-ai_custom_user_css:
  aot-ai_custom_user_js:
  aot-ai_custom_user_fonts:
  aot-ai_databases:
  aot-ai_ssl_certs:
  aot-ai_log:
  aot-ai_influxdb:
  aot-ai_grafana:
