# -*- coding: utf-8 -*-
# mcp_config.py - Centralized parameter management for AoT
# Generated by: 009_FIX_HARDCODING_AND_SECRETS (2026-03-22)
# Rule: All settings must be parameterized here or via environment variables.

import os

# ---------------------------------------------------------------------------
# AOT_ROOT_PATH: Physical root of the project (SMB mount SSoT)
# Override via env: AOT_ROOT
# ---------------------------------------------------------------------------
AOT_ROOT_PATH = os.getenv('AOT_ROOT', os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------------------
# DEVICE_IPS: Default IP addresses for IoT input modules
# Override each via the corresponding environment variable.
# These values are used as UI defaults; actual IPs are stored in the DB.
# ---------------------------------------------------------------------------
DEVICE_IPS = {
    'th1x':          os.getenv('DEVICE_IP_TH1X',          '192.168.0.100'),
    'th1x_ds18b20':  os.getenv('DEVICE_IP_TH1X_DS18B20',  '192.168.0.100'),
    'th1x_am2301':   os.getenv('DEVICE_IP_TH1X_AM2301',   '192.168.0.100'),
    'tasmota':       os.getenv('DEVICE_IP_TASMOTA',        '192.168.0.50'),
}

# ---------------------------------------------------------------------------
# BRIDGE_CONFIG: MCP bridge path resolution
# ---------------------------------------------------------------------------
BRIDGE_CONFIG = {
    'root_path': AOT_ROOT_PATH,
}

# ---------------------------------------------------------------------------
# HARDWARE_PROFILE: Edge-optimized capability gating
# Options: LOW | MEDIUM | HIGH
# ---------------------------------------------------------------------------
HARDWARE_PROFILE = os.getenv('HARDWARE_PROFILE', 'LOW')

# ---------------------------------------------------------------------------
# CONTEXT_LAYER_ROOT: Filesystem root for domain module YAML files.
# Override via env: CONTEXT_LAYER_ROOT
# Default: <project_root>/context_layer
# ---------------------------------------------------------------------------
CONTEXT_LAYER_ROOT = os.getenv(
    'CONTEXT_LAYER_ROOT',
    os.path.join(AOT_ROOT_PATH, 'context_layer'),
)

# ---------------------------------------------------------------------------
# CONTEXT_BROADCAST_INTERVAL_HOURS: How often the context broadcast job runs.
# Override via env: CONTEXT_BROADCAST_INTERVAL_HOURS
# Default: 1 hour
# ---------------------------------------------------------------------------
CONTEXT_BROADCAST_INTERVAL_HOURS = int(
    os.getenv('CONTEXT_BROADCAST_INTERVAL_HOURS', '1')
)

# ---------------------------------------------------------------------------
# CONTEXT_ACCUMULATION_DEPTH: Number of past AI summary records fetched
# during each context broadcast cycle for temporal reasoning.
# Override via env: CONTEXT_ACCUMULATION_DEPTH
# Default: 10 records
# ---------------------------------------------------------------------------
CONTEXT_ACCUMULATION_DEPTH = int(
    os.getenv('CONTEXT_ACCUMULATION_DEPTH', '10')
)

# ---------------------------------------------------------------------------
# REALTIME_ALERT_CHECK_MINUTES: How often the lightweight threshold-only
# anomaly check runs.  This job skips LLM summarization — it only reads
# device counts and fires SSE if thresholds are exceeded.
# Override via env: REALTIME_ALERT_CHECK_MINUTES
# Default: 5 minutes
# ---------------------------------------------------------------------------
REALTIME_ALERT_CHECK_MINUTES = int(
    os.getenv('REALTIME_ALERT_CHECK_MINUTES', '5')
)

# ---------------------------------------------------------------------------
# REALTIME_ALERT_COOLDOWN_MINUTES: Minimum quiet period between repeated
# SSE pushes for the same scope to avoid notification spam.
# Override via env: REALTIME_ALERT_COOLDOWN_MINUTES
# Default: 15 minutes
# ---------------------------------------------------------------------------
REALTIME_ALERT_COOLDOWN_MINUTES = int(
    os.getenv('REALTIME_ALERT_COOLDOWN_MINUTES', '15')
)

# ---------------------------------------------------------------------------
# UI_MAP_ADVICE_PANEL: AI Advice Panel positioning and styling configuration
# Used in AoT map widget template for dynamic, non-hardcoded layout
# All dimensions in pixels; override via environment variables
# ---------------------------------------------------------------------------
UI_MAP_ADVICE_PANEL = {
    # Measurement panel dimensions (source: aot-map-custom-controls.js)
    'measurement_panel_height_desktop': int(
        os.getenv('UI_MAP_ADVICE_MEASUREMENT_HEIGHT_DESKTOP', '80')
    ),
    'measurement_panel_height_mobile': int(
        os.getenv('UI_MAP_ADVICE_MEASUREMENT_HEIGHT_MOBILE', '60')
    ),
    'measurement_panel_bottom_offset': int(
        os.getenv('UI_MAP_ADVICE_MEASUREMENT_BOTTOM', '32')
    ),

    # Panel dimensions and positioning
    'panel_bottom_margin': int(
        os.getenv('UI_MAP_ADVICE_PANEL_BOTTOM_MARGIN', '32')
    ),
    'panel_max_width': int(
        os.getenv('UI_MAP_ADVICE_PANEL_MAX_WIDTH', '680')
    ),
    'panel_gap': int(
        os.getenv('UI_MAP_ADVICE_PANEL_GAP', '4')
    ),
    'panel_horizontal_margin': int(
        os.getenv('UI_MAP_ADVICE_PANEL_HORIZONTAL_MARGIN', '10')
    ),
    'panel_horizontal_margin_mobile': int(
        os.getenv('UI_MAP_ADVICE_PANEL_HORIZONTAL_MARGIN_MOBILE', '8')
    ),
    'panel_mobile_breakpoint': int(
        os.getenv('UI_MAP_ADVICE_PANEL_MOBILE_BREAKPOINT', '768')
    ),

    # Z-index positioning (below measurement panel to avoid occlusion)
    'panel_z_index': int(
        os.getenv('UI_MAP_ADVICE_PANEL_Z_INDEX', '1390')
    ),
    'measurement_panel_z_index': int(
        os.getenv('UI_MAP_ADVICE_MEASUREMENT_Z_INDEX', '1400')
    ),
}
