"""Add execution fields to AITask

Revision ID: 006c9c05ef29
Revises: 466a5358b695
Create Date: 2026-02-20 03:26:24.754506

"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(__file__, "../../../..")))

# from alembic_db.alembic_post_utils import write_revision_post_alembic

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '006c9c05ef29'
down_revision = '466a5358b695'
branch_labels = None
depends_on = None


def upgrade():
    # write_revision_post_alembic(revision)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('action_params', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True))
        batch_op.add_column(sa.Column('execution_result', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_task', schema=None) as batch_op:
        batch_op.drop_column('execution_result')
        batch_op.drop_column('action_params')
        batch_op.drop_column('target_id')
        batch_op.drop_column('action_type')

    # ### end Alembic commands ###
