"""Add system_prompt_template to ai_settings

Revision ID: 5d22ec6ddb24
Revises: 902da022547c
Create Date: 2026-02-21 00:31:57.393029

"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(__file__, "../../../..")))

# from alembic_db.alembic_post_utils import write_revision_post_alembic

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d22ec6ddb24'
down_revision = '902da022547c'
branch_labels = None
depends_on = None


def upgrade():
    # write_revision_post_alembic(revision)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_prompt_template', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_global_settings', schema=None) as batch_op:
        batch_op.drop_column('system_prompt_template')

    # ### end Alembic commands ###
