"""Initial Migration with Map Hierarchy

Revision ID: 718f314963bc
Revises: 
Create Date: 2025-12-16 13:33:03.025684

"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(__file__, "../../../..")))

# from alembic_db.alembic_post_utils import write_revision_post_alembic

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '718f314963bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    # write_revision_post_alembic(revision)

    # ### commands auto generated by Alembic - please adjust! ###
    if 'camera' not in tables:
        op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('library', sa.Text(), nullable=False),
    sa.Column('device', sa.Text(), nullable=False),
    sa.Column('opencv_device', sa.Integer(), nullable=True),
    sa.Column('hflip', sa.Boolean(), nullable=True),
    sa.Column('vflip', sa.Boolean(), nullable=True),
    sa.Column('rotation', sa.Integer(), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('contrast', sa.Float(), nullable=True),
    sa.Column('exposure', sa.Float(), nullable=True),
    sa.Column('gain', sa.Float(), nullable=True),
    sa.Column('hue', sa.Float(), nullable=True),
    sa.Column('saturation', sa.Float(), nullable=True),
    sa.Column('white_balance', sa.Float(), nullable=True),
    sa.Column('custom_options', sa.Text(), nullable=True),
    sa.Column('output_id', sa.String(length=36), nullable=True),
    sa.Column('output_duration', sa.Float(), nullable=True),
    sa.Column('cmd_pre_camera', sa.Text(), nullable=True),
    sa.Column('cmd_post_camera', sa.Text(), nullable=True),
    sa.Column('stream_started', sa.Boolean(), nullable=True),
    sa.Column('hide_still', sa.Boolean(), nullable=True),
    sa.Column('hide_timelapse', sa.Boolean(), nullable=True),
    sa.Column('url_still', sa.Text(), nullable=True),
    sa.Column('url_stream', sa.Text(), nullable=True),
    sa.Column('json_headers', sa.Text(), nullable=True),
    sa.Column('show_preview', sa.Boolean(), nullable=True),
    sa.Column('output_format', sa.Text(), nullable=True),
    sa.Column('timelapse_started', sa.Boolean(), nullable=True),
    sa.Column('timelapse_paused', sa.Boolean(), nullable=True),
    sa.Column('timelapse_start_time', sa.Float(), nullable=True),
    sa.Column('timelapse_end_time', sa.Float(), nullable=True),
    sa.Column('timelapse_interval', sa.Float(), nullable=True),
    sa.Column('timelapse_next_capture', sa.Float(), nullable=True),
    sa.Column('timelapse_capture_number', sa.Integer(), nullable=True),
    sa.Column('timelapse_last_file', sa.Text(), nullable=True),
    sa.Column('timelapse_last_ts', sa.Float(), nullable=True),
    sa.Column('still_last_file', sa.Text(), nullable=True),
    sa.Column('still_last_ts', sa.Float(), nullable=True),
    sa.Column('path_still', sa.Text(), nullable=True),
    sa.Column('path_timelapse', sa.Text(), nullable=True),
    sa.Column('path_video', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('resolution_stream_width', sa.Integer(), nullable=True),
    sa.Column('resolution_stream_height', sa.Integer(), nullable=True),
    sa.Column('stream_fps', sa.Integer(), nullable=True),
    sa.Column('picamera_shutter_speed', sa.Integer(), nullable=True),
    sa.Column('picamera_sharpness', sa.Integer(), nullable=True),
    sa.Column('picamera_iso', sa.Integer(), nullable=True),
    sa.Column('picamera_awb', sa.Text(), nullable=True),
    sa.Column('picamera_awb_gain_red', sa.Float(), nullable=True),
    sa.Column('picamera_awb_gain_blue', sa.Float(), nullable=True),
    sa.Column('picamera_exposure_mode', sa.Text(), nullable=True),
    sa.Column('picamera_meter_mode', sa.Text(), nullable=True),
    sa.Column('picamera_image_effect', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('unique_id')
    )
    if 'conditional' not in tables:
        op.create_table('conditional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('log_level_debug', sa.Boolean(), nullable=True),
    sa.Column('conditional_statement', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('conditional_import', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('conditional_initialize', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('conditional_status', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('period', sa.Float(), nullable=True),
    sa.Column('start_offset', sa.Float(), nullable=True),
    sa.Column('pyro_timeout', sa.Float(), nullable=True),
    sa.Column('use_pylint', sa.Boolean(), nullable=True),
    sa.Column('message_include_code', sa.Boolean(), nullable=True),
    sa.Column('custom_options', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'conditional_data' not in tables:
        op.create_table('conditional_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('conditional_id', sa.String(length=36), nullable=True),
    sa.Column('condition_type', sa.Text(), nullable=True),
    sa.Column('measurement', sa.Text(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('gpio_pin', sa.Integer(), nullable=True),
    sa.Column('output_id', sa.String(length=36), nullable=True),
    sa.Column('controller_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'conversion' not in tables:
        op.create_table('conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('convert_unit_from', sa.Text(), nullable=True),
    sa.Column('convert_unit_to', sa.Text(), nullable=True),
    sa.Column('equation', sa.Text(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'custom_controller' not in tables:
        op.create_table('custom_controller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('device', sa.Text(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('log_level_debug', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_source', sa.String(length=32), nullable=True),
    sa.Column('map_config_id', sa.String(length=36), nullable=True),
    sa.Column('custom_options', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'dashboard' not in tables:
        op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('unique_id')
    )
    if 'dashboard' in tables:
        indexes = [i['name'] for i in inspector.get_indexes('dashboard')]
        if 'ix_dashboard_sort_order' not in indexes:
            with op.batch_alter_table('dashboard', schema=None) as batch_op:
                batch_op.create_index(batch_op.f('ix_dashboard_sort_order'), ['sort_order'], unique=False)

    if 'device_measurements' not in tables:
        op.create_table('device_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('device_type', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('measurement', sa.Text(), nullable=True),
    sa.Column('measurement_type', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('rescale_method', sa.Text(), nullable=True),
    sa.Column('rescale_equation', sa.Text(), nullable=True),
    sa.Column('invert_scale', sa.Boolean(), nullable=True),
    sa.Column('rescaled_measurement', sa.Text(), nullable=True),
    sa.Column('rescaled_unit', sa.Text(), nullable=True),
    sa.Column('scale_from_min', sa.Float(), nullable=True),
    sa.Column('scale_from_max', sa.Float(), nullable=True),
    sa.Column('scale_to_min', sa.Float(), nullable=True),
    sa.Column('scale_to_max', sa.Float(), nullable=True),
    sa.Column('conversion_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'displayorder' not in tables:
        op.create_table('displayorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lcd', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('remote_host', sa.Text(), nullable=True),
    sa.Column('timer', sa.Text(), nullable=True),
    sa.Column('math', sa.Text(), nullable=True),
    sa.Column('inputs', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('dashboard', sa.Text(), nullable=True),
    sa.Column('function', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    if 'energy_usage' not in tables:
        op.create_table('energy_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('measurement_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'function' not in tables:
        op.create_table('function',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('function_type', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('log_level_debug', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_source', sa.String(length=32), nullable=True),
    sa.Column('marker_icon', sa.Text(), nullable=True),
    sa.Column('marker_color', sa.Text(), nullable=True),
    sa.Column('marker_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'function_actions' not in tables:
        op.create_table('function_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('function_id', sa.String(length=36), nullable=True),
    sa.Column('function_type', sa.Text(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=True),
    sa.Column('custom_options', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('pause_duration', sa.Float(), nullable=True),
    sa.Column('do_unique_id', sa.String(length=36), nullable=True),
    sa.Column('do_action_string', sa.Text(), nullable=True),
    sa.Column('do_output_state', sa.Text(), nullable=True),
    sa.Column('do_output_amount', sa.Float(), nullable=True),
    sa.Column('do_output_duration', sa.Float(), nullable=True),
    sa.Column('do_output_pwm', sa.Float(), nullable=True),
    sa.Column('do_output_pwm2', sa.Float(), nullable=True),
    sa.Column('do_camera_duration', sa.Float(), nullable=True),
    sa.Column('remote', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('send_times', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'function_channel' not in tables:
        op.create_table('function_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('function_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('custom_options', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'input' not in tables:
        op.create_table('input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('device', sa.Text(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('log_level_debug', sa.Boolean(), nullable=True),
    sa.Column('is_preset', sa.Boolean(), nullable=True),
    sa.Column('preset_name', sa.Text(), nullable=True),
    sa.Column('interface', sa.Text(), nullable=True),
    sa.Column('period', sa.Float(), nullable=True),
    sa.Column('start_offset', sa.Float(), nullable=True),
    sa.Column('power_output_id', sa.String(length=36), nullable=True),
    sa.Column('resolution', sa.Integer(), nullable=True),
    sa.Column('resolution_2', sa.Integer(), nullable=True),
    sa.Column('sensitivity', sa.Integer(), nullable=True),
    sa.Column('thermocouple_type', sa.Text(), nullable=True),
    sa.Column('ref_ohm', sa.Integer(), nullable=True),
    sa.Column('calibrate_sensor_measure', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_source', sa.Text(), nullable=True),
    sa.Column('location_updated_utc', sa.DateTime(), nullable=True),
    sa.Column('marker_icon', sa.Text(), nullable=True),
    sa.Column('marker_color', sa.Text(), nullable=True),
    sa.Column('marker_size', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('gpio_location', sa.Integer(), nullable=True),
    sa.Column('map_config_id', sa.String(length=36), nullable=True),
    sa.Column('map_overlay_id', sa.Integer(), nullable=True),
    sa.Column('i2c_location', sa.Text(), nullable=True),
    sa.Column('i2c_bus', sa.Integer(), nullable=True),
    sa.Column('ftdi_location', sa.Text(), nullable=True),
    sa.Column('uart_location', sa.Text(), nullable=True),
    sa.Column('baud_rate', sa.Integer(), nullable=True),
    sa.Column('pin_clock', sa.Integer(), nullable=True),
    sa.Column('pin_cs', sa.Integer(), nullable=True),
    sa.Column('pin_mosi', sa.Integer(), nullable=True),
    sa.Column('pin_miso', sa.Integer(), nullable=True),
    sa.Column('bt_adapter', sa.Text(), nullable=True),
    sa.Column('switch_edge', sa.Text(), nullable=True),
    sa.Column('switch_bouncetime', sa.Integer(), nullable=True),
    sa.Column('switch_reset_period', sa.Integer(), nullable=True),
    sa.Column('pre_output_id', sa.String(length=36), nullable=True),
    sa.Column('pre_output_duration', sa.Float(), nullable=True),
    sa.Column('pre_output_during_measure', sa.Boolean(), nullable=True),
    sa.Column('sht_voltage', sa.Text(), nullable=True),
    sa.Column('adc_gain', sa.Integer(), nullable=True),
    sa.Column('adc_resolution', sa.Integer(), nullable=True),
    sa.Column('adc_sample_speed', sa.Text(), nullable=True),
    sa.Column('cmd_command', sa.Text(), nullable=True),
    sa.Column('weighting', sa.Float(), nullable=True),
    sa.Column('rpm_pulses_per_rev', sa.Float(), nullable=True),
    sa.Column('sample_time', sa.Float(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('times_check', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('custom_options', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'input_channel' not in tables:
        op.create_table('input_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('input_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('custom_options', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'irrigation_design' not in tables:
        op.create_table('irrigation_design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('boundary_json', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('rows_json', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('sprinklers_json', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('config_json', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'map_config' not in tables:
        op.create_table('map_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('zoom', sa.Integer(), nullable=True),
    sa.Column('is_device_owned', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('style_url', sa.Text(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('use_satellite', sa.Boolean(), nullable=True),
    sa.Column('providers', sa.Text(), nullable=True),
    sa.Column('state_json', sa.Text(), nullable=True),
    sa.Column('map_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'map_global_settings' not in tables:
        op.create_table('map_global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('providers', sa.Text(), nullable=True),
    sa.Column('keys', sa.Text(), nullable=True),
    sa.Column('zoom', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    if 'map_overlay' not in tables:
        op.create_table('map_overlay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('layer_group', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('feature', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('meta_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['map_overlay.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    if 'map_overlay' in tables:
        indexes = [i['name'] for i in inspector.get_indexes('map_overlay')]
        with op.batch_alter_table('map_overlay', schema=None) as batch_op:
            if 'ix_map_overlay_device_id' not in indexes:
                batch_op.create_index(batch_op.f('ix_map_overlay_device_id'), ['device_id'], unique=False)
            if 'ix_map_overlay_map_id' not in indexes:
                batch_op.create_index(batch_op.f('ix_map_overlay_map_id'), ['map_id'], unique=False)
            if 'ix_map_overlay_parent_id' not in indexes:
                batch_op.create_index(batch_op.f('ix_map_overlay_parent_id'), ['parent_id'], unique=False)
            if 'ix_map_overlay_type' not in indexes:
                batch_op.create_index(batch_op.f('ix_map_overlay_type'), ['type'], unique=False)

    if 'measurements' not in tables:
        op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name_safe', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('units', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'method' not in tables:
        op.create_table('method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('method_type', sa.Text(), nullable=True),
    sa.Column('method_order', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'method_data' not in tables:
        op.create_table('method_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('method_id', sa.String(length=36), nullable=True),
    sa.Column('time_start', sa.Text(), nullable=True),
    sa.Column('time_end', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('duration_end', sa.Float(), nullable=True),
    sa.Column('output_id', sa.String(length=36), nullable=True),
    sa.Column('output_state', sa.Text(), nullable=True),
    sa.Column('output_duration', sa.Float(), nullable=True),
    sa.Column('setpoint_start', sa.Float(), nullable=True),
    sa.Column('setpoint_end', sa.Float(), nullable=True),
    sa.Column('amplitude', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('shift_angle', sa.Float(), nullable=True),
    sa.Column('shift_y', sa.Float(), nullable=True),
    sa.Column('x0', sa.Float(), nullable=True),
    sa.Column('y0', sa.Float(), nullable=True),
    sa.Column('x1', sa.Float(), nullable=True),
    sa.Column('y1', sa.Float(), nullable=True),
    sa.Column('x2', sa.Float(), nullable=True),
    sa.Column('y2', sa.Float(), nullable=True),
    sa.Column('x3', sa.Float(), nullable=True),
    sa.Column('y3', sa.Float(), nullable=True),
    sa.Column('linked_method_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'misc' not in tables:
        op.create_table('misc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dismiss_notification', sa.Boolean(), nullable=True),
    sa.Column('force_https', sa.Boolean(), nullable=True),
    sa.Column('hide_alert_info', sa.Boolean(), nullable=True),
    sa.Column('hide_alert_success', sa.Boolean(), nullable=True),
    sa.Column('hide_alert_warning', sa.Boolean(), nullable=True),
    sa.Column('hide_tooltips', sa.Boolean(), nullable=True),
    sa.Column('grid_cell_height', sa.Integer(), nullable=True),
    sa.Column('login_message', sa.Text(), nullable=True),
    sa.Column('max_amps', sa.Float(), nullable=True),
    sa.Column('output_usage_cost', sa.Float(), nullable=True),
    sa.Column('output_usage_currency', sa.Text(), nullable=True),
    sa.Column('output_usage_dayofmonth', sa.Integer(), nullable=True),
    sa.Column('output_usage_volts', sa.Integer(), nullable=True),
    sa.Column('output_usage_report_gen', sa.Boolean(), nullable=True),
    sa.Column('output_usage_report_span', sa.Text(), nullable=True),
    sa.Column('output_usage_report_day', sa.Integer(), nullable=True),
    sa.Column('output_usage_report_hour', sa.Integer(), nullable=True),
    sa.Column('sample_rate_controller_conditional', sa.Float(), nullable=True),
    sa.Column('sample_rate_controller_function', sa.Float(), nullable=True),
    sa.Column('sample_rate_controller_input', sa.Float(), nullable=True),
    sa.Column('sample_rate_controller_math', sa.Float(), nullable=True),
    sa.Column('sample_rate_controller_output', sa.Float(), nullable=True),
    sa.Column('sample_rate_controller_pid', sa.Float(), nullable=True),
    sa.Column('sample_rate_controller_widget', sa.Float(), nullable=True),
    sa.Column('stats_opt_out', sa.Boolean(), nullable=True),
    sa.Column('enable_upgrade_check', sa.Boolean(), nullable=True),
    sa.Column('aot_upgrade_available', sa.Boolean(), nullable=True),
    sa.Column('rpyc_timeout', sa.Integer(), nullable=True),
    sa.Column('daemon_debug_mode', sa.Boolean(), nullable=True),
    sa.Column('net_test_ip', sa.String(length=16), nullable=True),
    sa.Column('net_test_port', sa.Integer(), nullable=True),
    sa.Column('net_test_timeout', sa.Integer(), nullable=True),
    sa.Column('default_login_page', sa.String(length=16), nullable=True),
    sa.Column('brand_display', sa.String(length=36), nullable=True),
    sa.Column('title_display', sa.String(length=36), nullable=True),
    sa.Column('hostname_override', sa.String(length=36), nullable=True),
    sa.Column('brand_image', sa.BLOB(), nullable=True),
    sa.Column('brand_image_height', sa.Integer(), nullable=True),
    sa.Column('favicon_display', sa.String(length=16), nullable=True),
    sa.Column('brand_favicon', sa.BLOB(), nullable=True),
    sa.Column('custom_css', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('custom_layout', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('map_latitude', sa.Float(), nullable=True),
    sa.Column('map_longitude', sa.Float(), nullable=True),
    sa.Column('map_location_label', sa.Text(), nullable=True),
    sa.Column('measurement_db_retention_policy', sa.String(length=36), nullable=True),
    sa.Column('measurement_db_name', sa.String(length=36), nullable=True),
    sa.Column('measurement_db_version', sa.String(length=36), nullable=True),
    sa.Column('measurement_db_host', sa.String(length=36), nullable=True),
    sa.Column('measurement_db_port', sa.String(length=36), nullable=True),
    sa.Column('measurement_db_user', sa.String(length=36), nullable=True),
    sa.Column('measurement_db_password', sa.String(length=36), nullable=True),
    sa.Column('measurement_db_dbname', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    if 'note_tags' not in tables:
        op.create_table('note_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'notes' not in tables:
        op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('files', sa.Text(), nullable=True),
    sa.Column('note', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'output' not in tables:
        op.create_table('output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('output_type', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('size_y', sa.Integer(), nullable=True),
    sa.Column('log_level_debug', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_source', sa.Text(), nullable=True),
    sa.Column('map_config_id', sa.String(length=36), nullable=True),
    sa.Column('map_overlay_id', sa.Integer(), nullable=True),
    sa.Column('location_updated_utc', sa.DateTime(), nullable=True),
    sa.Column('marker_icon', sa.Text(), nullable=True),
    sa.Column('marker_color', sa.Text(), nullable=True),
    sa.Column('marker_size', sa.Integer(), nullable=True),
    sa.Column('interface', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('i2c_location', sa.Text(), nullable=True),
    sa.Column('i2c_bus', sa.Integer(), nullable=True),
    sa.Column('ftdi_location', sa.Text(), nullable=True),
    sa.Column('uart_location', sa.Text(), nullable=True),
    sa.Column('baud_rate', sa.Integer(), nullable=True),
    sa.Column('custom_options', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('pin', sa.Integer(), nullable=True),
    sa.Column('on_state', sa.Boolean(), nullable=True),
    sa.Column('amps', sa.Float(), nullable=True),
    sa.Column('on_until', sa.DateTime(), nullable=True),
    sa.Column('off_until', sa.DateTime(), nullable=True),
    sa.Column('last_duration', sa.Float(), nullable=True),
    sa.Column('on_duration', sa.Boolean(), nullable=True),
    sa.Column('protocol', sa.Integer(), nullable=True),
    sa.Column('pulse_length', sa.Integer(), nullable=True),
    sa.Column('linux_command_user', sa.Text(), nullable=True),
    sa.Column('on_command', sa.Text(), nullable=True),
    sa.Column('off_command', sa.Text(), nullable=True),
    sa.Column('pwm_command', sa.Text(), nullable=True),
    sa.Column('force_command', sa.Boolean(), nullable=True),
    sa.Column('trigger_functions_at_start', sa.Boolean(), nullable=True),
    sa.Column('state_startup', sa.Text(), nullable=True),
    sa.Column('startup_value', sa.Float(), nullable=True),
    sa.Column('state_shutdown', sa.Text(), nullable=True),
    sa.Column('shutdown_value', sa.Float(), nullable=True),
    sa.Column('pwm_hertz', sa.Integer(), nullable=True),
    sa.Column('pwm_library', sa.Text(), nullable=True),
    sa.Column('pwm_invert_signal', sa.Boolean(), nullable=True),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('output_mode', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'output_channel' not in tables:
        op.create_table('output_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('output_id', sa.Text(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('custom_options', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'pid' not in tables:
        op.create_table('pid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('is_held', sa.Boolean(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=True),
    sa.Column('is_preset', sa.Boolean(), nullable=True),
    sa.Column('log_level_debug', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_source', sa.String(length=32), nullable=True),
    sa.Column('preset_name', sa.Text(), nullable=True),
    sa.Column('period', sa.Float(), nullable=True),
    sa.Column('start_offset', sa.Float(), nullable=True),
    sa.Column('max_measure_age', sa.Float(), nullable=True),
    sa.Column('measurement', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('setpoint', sa.Float(), nullable=True),
    sa.Column('band', sa.Float(), nullable=True),
    sa.Column('p', sa.Float(), nullable=True),
    sa.Column('i', sa.Float(), nullable=True),
    sa.Column('d', sa.Float(), nullable=True),
    sa.Column('integrator_min', sa.Float(), nullable=True),
    sa.Column('integrator_max', sa.Float(), nullable=True),
    sa.Column('raise_output_id', sa.String(length=36), nullable=True),
    sa.Column('raise_output_type', sa.String(length=36), nullable=True),
    sa.Column('raise_min_duration', sa.Float(), nullable=True),
    sa.Column('raise_max_duration', sa.Float(), nullable=True),
    sa.Column('raise_min_off_duration', sa.Float(), nullable=True),
    sa.Column('raise_always_min_pwm', sa.Boolean(), nullable=True),
    sa.Column('lower_output_id', sa.String(length=36), nullable=True),
    sa.Column('lower_output_type', sa.String(length=36), nullable=True),
    sa.Column('lower_min_duration', sa.Float(), nullable=True),
    sa.Column('lower_max_duration', sa.Float(), nullable=True),
    sa.Column('lower_min_off_duration', sa.Float(), nullable=True),
    sa.Column('lower_always_min_pwm', sa.Boolean(), nullable=True),
    sa.Column('send_lower_as_negative', sa.Boolean(), nullable=True),
    sa.Column('store_lower_as_negative', sa.Boolean(), nullable=True),
    sa.Column('setpoint_tracking_type', sa.Text(), nullable=True),
    sa.Column('setpoint_tracking_id', sa.String(length=36), nullable=True),
    sa.Column('setpoint_tracking_max_age', sa.Float(), nullable=True),
    sa.Column('method_start_time', sa.Text(), nullable=True),
    sa.Column('method_end_time', sa.Text(), nullable=True),
    sa.Column('autotune_activated', sa.Boolean(), nullable=True),
    sa.Column('autotune_noiseband', sa.Float(), nullable=True),
    sa.Column('autotune_outstep', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'remote' not in tables:
        op.create_table('remote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'roles' not in tables:
        op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('edit_settings', sa.Boolean(), nullable=False),
    sa.Column('edit_controllers', sa.Boolean(), nullable=False),
    sa.Column('edit_users', sa.Boolean(), nullable=False),
    sa.Column('view_settings', sa.Boolean(), nullable=False),
    sa.Column('view_camera', sa.Boolean(), nullable=False),
    sa.Column('view_stats', sa.Boolean(), nullable=False),
    sa.Column('view_logs', sa.Boolean(), nullable=False),
    sa.Column('reset_password', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('unique_id')
    )
    if 'smtp' not in tables:
        op.create_table('smtp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('protocol', sa.Text(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('user', sa.Text(), nullable=True),
    sa.Column('passw', sa.Text(), nullable=True),
    sa.Column('email_from', sa.Text(), nullable=True),
    sa.Column('hourly_max', sa.Integer(), nullable=True),
    sa.Column('email_count', sa.Integer(), nullable=True),
    sa.Column('smtp_wait_timer', sa.Integer(), nullable=True),
    sa.Column('ssl', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    if 'trigger' not in tables:
        op.create_table('trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_type', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('log_level_debug', sa.Boolean(), nullable=True),
    sa.Column('unique_id_1', sa.String(length=36), nullable=True),
    sa.Column('unique_id_2', sa.String(length=36), nullable=True),
    sa.Column('unique_id_3', sa.String(length=36), nullable=True),
    sa.Column('output_state', sa.Text(), nullable=True),
    sa.Column('output_duration', sa.Float(), nullable=True),
    sa.Column('output_duty_cycle', sa.Float(), nullable=True),
    sa.Column('rise_or_set', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_source', sa.String(length=32), nullable=True),
    sa.Column('date_offset_days', sa.Integer(), nullable=True),
    sa.Column('time_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('period', sa.Float(), nullable=True),
    sa.Column('timer_start_offset', sa.Integer(), nullable=True),
    sa.Column('timer_start_time', sa.Text(), nullable=True),
    sa.Column('timer_end_time', sa.Text(), nullable=True),
    sa.Column('program', sa.Text(), nullable=True),
    sa.Column('word', sa.Text(), nullable=True),
    sa.Column('method_start_time', sa.Text(), nullable=True),
    sa.Column('method_end_time', sa.Text(), nullable=True),
    sa.Column('trigger_actions_at_period', sa.Boolean(), nullable=True),
    sa.Column('trigger_actions_at_start', sa.Boolean(), nullable=True),
    sa.Column('measurement', sa.Text(), nullable=True),
    sa.Column('edge_detected', sa.Text(), nullable=True),
    sa.Column('zenith', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'units' not in tables:
        op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name_safe', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'users' not in tables:
        op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('api_key', sa.BLOB(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('theme', sa.VARCHAR(length=64), nullable=True),
    sa.Column('landing_page', sa.Text(), nullable=True),
    sa.Column('index_page', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('password_reset_code', sa.Text(), nullable=True),
    sa.Column('password_reset_code_expiration', sa.DateTime(), nullable=True),
    sa.Column('password_reset_last_request', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('unique_id')
    )
    if 'users' in tables:
        indexes = [i['name'] for i in inspector.get_indexes('users')]
        with op.batch_alter_table('users', schema=None) as batch_op:
            if 'ix_users_email' not in indexes:
                batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
            if 'ix_users_name' not in indexes:
                batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=True)

    if 'widget' not in tables:
        op.create_table('widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('graph_type', sa.Text(), nullable=True),
    sa.Column('dashboard_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('log_level_debug', sa.Boolean(), nullable=True),
    sa.Column('font_em_name', sa.Float(), nullable=True),
    sa.Column('enable_drag_handle', sa.Boolean(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('custom_options', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('enable_header_buttons', sa.Boolean(), nullable=True),
    sa.Column('period', sa.Float(), nullable=True),
    sa.Column('refresh_duration', sa.Integer(), nullable=True),
    sa.Column('x_axis_duration', sa.Integer(), nullable=True),
    sa.Column('custom_yaxes', sa.Text(), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.Column('enable_status', sa.Boolean(), nullable=True),
    sa.Column('enable_value', sa.Boolean(), nullable=True),
    sa.Column('enable_name', sa.Boolean(), nullable=True),
    sa.Column('enable_unit', sa.Boolean(), nullable=True),
    sa.Column('enable_measurement', sa.Boolean(), nullable=True),
    sa.Column('enable_channel', sa.Boolean(), nullable=True),
    sa.Column('enable_timestamp', sa.Boolean(), nullable=True),
    sa.Column('pid_ids', sa.Text(), nullable=True),
    sa.Column('output_ids', sa.Text(), nullable=True),
    sa.Column('math_ids', sa.Text(), nullable=True),
    sa.Column('note_tag_ids', sa.Text(), nullable=True),
    sa.Column('input_ids_measurements', sa.Text(), nullable=True),
    sa.Column('enable_navbar', sa.Boolean(), nullable=True),
    sa.Column('enable_rangeselect', sa.Boolean(), nullable=True),
    sa.Column('enable_export', sa.Boolean(), nullable=True),
    sa.Column('enable_title', sa.Boolean(), nullable=True),
    sa.Column('enable_auto_refresh', sa.Boolean(), nullable=True),
    sa.Column('enable_xaxis_reset', sa.Boolean(), nullable=True),
    sa.Column('enable_manual_y_axis', sa.Boolean(), nullable=True),
    sa.Column('enable_start_on_tick', sa.Boolean(), nullable=True),
    sa.Column('enable_end_on_tick', sa.Boolean(), nullable=True),
    sa.Column('enable_align_ticks', sa.Boolean(), nullable=True),
    sa.Column('use_custom_colors', sa.Boolean(), nullable=True),
    sa.Column('custom_colors', sa.Text(), nullable=True),
    sa.Column('disable_data_grouping', sa.Text(), nullable=True),
    sa.Column('max_measure_age', sa.Integer(), nullable=True),
    sa.Column('stops', sa.Integer(), nullable=True),
    sa.Column('range_colors', sa.Text(), nullable=True),
    sa.Column('y_axis_min', sa.Float(), nullable=True),
    sa.Column('y_axis_max', sa.Float(), nullable=True),
    sa.Column('option_invert', sa.Boolean(), nullable=True),
    sa.Column('font_em_value', sa.Float(), nullable=True),
    sa.Column('font_em_timestamp', sa.Float(), nullable=True),
    sa.Column('enable_output_controls', sa.Boolean(), nullable=True),
    sa.Column('show_pid_info', sa.Boolean(), nullable=True),
    sa.Column('show_set_setpoint', sa.Boolean(), nullable=True),
    sa.Column('camera_id', sa.String(length=36), nullable=True),
    sa.Column('camera_image_type', sa.Text(), nullable=True),
    sa.Column('camera_max_age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    if 'map_dependency' not in tables:
        op.create_table('map_dependency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['map_overlay.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    if 'map_dependency' in tables:
        indexes = [i['name'] for i in inspector.get_indexes('map_dependency')]
        with op.batch_alter_table('map_dependency', schema=None) as batch_op:
            if 'ix_map_dependency_source_id' not in indexes:
                batch_op.create_index(batch_op.f('ix_map_dependency_source_id'), ['source_id'], unique=False)
            if 'ix_map_dependency_target_id' not in indexes:
                batch_op.create_index(batch_op.f('ix_map_dependency_target_id'), ['target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_dependency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_dependency_target_id'))
        batch_op.drop_index(batch_op.f('ix_map_dependency_source_id'))

    op.drop_table('map_dependency')
    op.drop_table('widget')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('trigger')
    op.drop_table('smtp')
    op.drop_table('roles')
    op.drop_table('remote')
    op.drop_table('pid')
    op.drop_table('output_channel')
    op.drop_table('output')
    op.drop_table('notes')
    op.drop_table('note_tags')
    op.drop_table('misc')
    op.drop_table('method_data')
    op.drop_table('method')
    op.drop_table('measurements')
    with op.batch_alter_table('map_overlay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_overlay_type'))
        batch_op.drop_index(batch_op.f('ix_map_overlay_parent_id'))
        batch_op.drop_index(batch_op.f('ix_map_overlay_map_id'))
        batch_op.drop_index(batch_op.f('ix_map_overlay_device_id'))

    op.drop_table('map_overlay')
    op.drop_table('map_global_settings')
    op.drop_table('map_config')
    op.drop_table('irrigation_design')
    op.drop_table('input_channel')
    op.drop_table('input')
    op.drop_table('function_channel')
    op.drop_table('function_actions')
    op.drop_table('function')
    op.drop_table('energy_usage')
    op.drop_table('displayorder')
    op.drop_table('device_measurements')
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_sort_order'))

    op.drop_table('dashboard')
    op.drop_table('custom_controller')
    op.drop_table('conversion')
    op.drop_table('conditional_data')
    op.drop_table('conditional')
    op.drop_table('camera')
    # ### end Alembic commands ###
