"""Add unique_id to GeoShape

Revision ID: b2275c9c445a
Revises: c1d2e3f4a5b6
Create Date: 2026-03-23 09:07:15.839979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2275c9c445a'
down_revision = 'c1d2e3f4a5b6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('geo_shape', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_geo_shape_unique_id', ['unique_id'])

    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###

    op.create_table('ai_agent_skeleton',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('agent_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_mcp', sa.BOOLEAN(), nullable=False),
    sa.Column('mcp_tool_registry_json', sa.TEXT(), nullable=True),
    sa.Column('authority_level', sa.INTEGER(), nullable=True),
    sa.Column('system_prompt', sa.TEXT(), nullable=True),
    sa.Column('custom_options_json', sa.TEXT(), nullable=True),
    sa.Column('is_activated', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    # ### end Alembic commands ###
