"""Add AIUserProfile model

Revision ID: b58bdb9fb18f
Revises: 5d22ec6ddb24
Create Date: 2026-02-22 10:40:44.856975

"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(__file__, "../../../..")))

# from alembic_db.alembic_post_utils import write_revision_post_alembic

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58bdb9fb18f'
down_revision = '5d22ec6ddb24'
branch_labels = None
depends_on = None


def upgrade():
    # write_revision_post_alembic(revision)

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
