"""Add GridStack layout fields to AI models

Revision ID: fa3f6b126917
Revises: 718f314963c3
Create Date: 2026-02-15 19:50:31.400342

"""
import sys
import os

sys.path.append(os.path.abspath(os.path.join(__file__, "../../../..")))

# from alembic_db.alembic_post_utils import write_revision_post_alembic

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fa3f6b126917'
down_revision = '718f314963c3'
branch_labels = None
depends_on = None


def upgrade():
    # write_revision_post_alembic(revision)

    # ### commands auto generated by Alembic - please adjust! ###
    # Safe drop for tables that might not exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'map_dependency' in tables:
        op.drop_table('map_dependency')
    if 'map_global_settings' in tables:
        op.drop_table('map_global_settings')
    if 'map_overlay' in tables:
        op.drop_table('map_overlay')
    if 'map_config' in tables:
        op.drop_table('map_config')
    ai_agent_cols = [c['name'] for c in inspector.get_columns('ai_agent')]
    with op.batch_alter_table('ai_agent', schema=None) as batch_op:
        if 'position_x' not in ai_agent_cols:
            batch_op.add_column(sa.Column('position_x', sa.Integer(), nullable=True))
        if 'position_y' not in ai_agent_cols:
            batch_op.add_column(sa.Column('position_y', sa.Integer(), nullable=True))
        if 'width' not in ai_agent_cols:
            batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        if 'height' not in ai_agent_cols:
            batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))

    ai_entry_cols = [c['name'] for c in inspector.get_columns('ai_entry')]
    with op.batch_alter_table('ai_entry', schema=None) as batch_op:
        if 'position_x' not in ai_entry_cols:
            batch_op.add_column(sa.Column('position_x', sa.Integer(), nullable=True))
        if 'position_y' not in ai_entry_cols:
            batch_op.add_column(sa.Column('position_y', sa.Integer(), nullable=True))
        if 'width' not in ai_entry_cols:
            batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        if 'height' not in ai_entry_cols:
            batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_entry', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('position_y')
        batch_op.drop_column('position_x')

    with op.batch_alter_table('ai_agent', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('position_y')
        batch_op.drop_column('position_x')

    op.create_table('map_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('zoom', sa.INTEGER(), nullable=True),
    sa.Column('is_device_owned', sa.BOOLEAN(), nullable=True),
    sa.Column('provider', sa.VARCHAR(length=32), nullable=True),
    sa.Column('style_url', sa.TEXT(), nullable=True),
    sa.Column('api_key', sa.TEXT(), nullable=True),
    sa.Column('use_satellite', sa.BOOLEAN(), nullable=True),
    sa.Column('providers', sa.TEXT(), nullable=True),
    sa.Column('state_json', sa.TEXT(), nullable=True),
    sa.Column('map_locked', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('map_overlay',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('map_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('layer_group', sa.VARCHAR(length=64), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('feature', sqlite.JSON(), nullable=False),
    sa.Column('meta_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('channel_id', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['map_overlay.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('map_overlay', schema=None) as batch_op:
        batch_op.create_index('ix_map_overlay_channel_id', ['channel_id'], unique=False)

    op.create_table('map_global_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('providers', sa.TEXT(), nullable=True),
    sa.Column('keys', sa.TEXT(), nullable=True),
    sa.Column('zoom', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('map_dependency',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('map_id', sa.VARCHAR(length=64), server_default=sa.text("'default_map'"), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['map_overlay.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('map_dependency', schema=None) as batch_op:
        batch_op.create_index('ix_map_dependency_map_id', ['map_id'], unique=False)

    # ### end Alembic commands ###
