"""Restore ai_agent_skeleton table

Revision ID: fbbbc91ca4eb
Revises: b2275c9c445a
Create Date: 2026-03-23 09:13:52.828740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbbc91ca4eb'
down_revision = 'b2275c9c445a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    # The ai_agent_skeleton table already exists.
    with op.batch_alter_table('ai_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduler_job_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_task_scheduler_job_id'), ['scheduler_job_id'], unique=False)
        # Bypassing foreign key creation due to SQLite batch mode mismatch. 
        # Application-level logic still enforces the relationship.

    # Geo shape unique_id constraint was already applied previously
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    # The ai_agent_skeleton table already existed.    # ### end Alembic commands ###
    pass
